Katrina Kalashnikova
CS362
 
    My inputChar generates a random number and retrieves that value from the ASCii table. 
    It then returns that random value. 

    *inputString() untilizes inputChar. 
    It first generates a random number between 5 and 20. 
    It then loops through and populates an array "str" with that many characters. 
    Each character is generated by calling inputChar and appending that random char to the end of the string. 

    These two functions will cycle through ASCii characters and generate strings/output characters. 
    Although there is a small bias toward certain characters, all characters will be generated with enough runs. 
